[package]
name = "enum_inner_method"
version = "0.1.0"
edition = "2024"
default-run = "enum_inner_method"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"

[dev-dependencies]
trybuild = "1.0.104"

[[test]]
name = "tests"
path = "tests/test.rs"

